---
# This Playbook runs plays to install python2.7 environment

- name: Make directory for installing
  file: path=/root/liqin/autoscaling/python2.7 state=directory

- name: Upload python archive
  copy: src=Python-2.7.11.tgz dest=/root/liqin/autoscaling/python2.7/Python-2.7.11.tgz

- name: Upload install shell script
  copy: src=install.sh dest=/root/liqin/autoscaling//python2.7/install.sh mode=655

- name: Install the latest version of openssl-devel
  yum: name=openssl-devel

- name: Install python2.7 environment
  shell: ./install.sh
  args:
    chdir: /root/liqin/autoscaling/python2.7

- name: Remove directory for installing
  file: path=/root/liqin/autoscaling/python2.7 state=absent

- name: Create virtual environment
  command: virtualenv -p python2.7 python2.7Env
  args:
    chdir: /root/liqin/autoscaling